packages:
  - "apps/sdkwork-local-router-pc"
  - "apps/sdkwork-local-router-pc/packages/*"
  - "apps/sdkwork-modelkit-pc"
  - "apps/sdkwork-modelkit-pc/packages/*"

allowBuilds:
  '@google/genai': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false

catalog:
  '@vitejs/plugin-react': ^5.0.0
  typescript: ~5.8.2
  vite: ^6.2.3
  react: ^19.0.0
  react-dom: ^19.0.0
