//! sdkwork-routes-local-router-backend-api gateway route manifest (materialized from the authored
//! route definitions; business routes use dual-token auth).

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/upstreams",
        "local_router",
        "localRouter.upstreams.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/logs",
        "local_router",
        "localRouter.logs.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/plugins",
        "local_router",
        "localRouter.plugins.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/plugins/decision",
        "local_router",
        "localRouter.plugins.decision",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/api_groups",
        "local_router",
        "localRouter.apiGroups.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/accounts",
        "local_router",
        "localRouter.accounts.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/accounts",
        "local_router",
        "localRouter.accounts.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/client_api_keys",
        "local_router",
        "localRouter.clientApiKeys.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/client_api_keys",
        "local_router",
        "localRouter.clientApiKeys.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/local_router/client_api_keys/{clientApiKeyId}",
        "local_router",
        "localRouter.clientApiKeys.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/local_router/accounts/{accountId}",
        "local_router",
        "localRouter.accounts.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/local_router/accounts/{accountId}",
        "local_router",
        "localRouter.accounts.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/accounts/{accountId}/toggle",
        "local_router",
        "localRouter.accounts.toggle",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/model_route_mappings",
        "local_router",
        "localRouter.modelRouteMappings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/model_route_mappings",
        "local_router",
        "localRouter.modelRouteMappings.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/local_router/model_route_mappings/{modelRouteMappingId}",
        "local_router",
        "localRouter.modelRouteMappings.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/usages",
        "local_router",
        "localRouter.usages.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/usages/summary",
        "local_router",
        "localRouter.usages.summary",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/local_router/health",
        "local_router",
        "localRouter.health.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/health/{accountName}/open",
        "local_router",
        "localRouter.health.open",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/health/{accountName}/close",
        "local_router",
        "localRouter.health.close",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/local_router/strategy",
        "local_router",
        "localRouter.strategy.set",
    ),
];

pub fn gateway_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
